vim.keymap.set('n', '<Leader><Right>', function() require('dap').continue() end)
vim.keymap.set('n', '<Leader><Up>', function() require('dap').step_over() end)
vim.keymap.set('n', '<Leader><Down>', function() require('dap').step_into() end)
vim.keymap.set('n', '<Leader><Left>', function() require('dap').step_out() end)
vim.keymap.set('n', '<Leader>b', function() require('dap').toggle_breakpoint() end)
vim.keymap.set('n', '<Leader>dr', function() require('dap').repl.open() end)
vim.keymap.set({'n', 'v'}, '<Leader>dh', function()
    require('dap.ui.widgets').hover()
end)
vim.keymap.set({'n', 'v'}, '<Leader>dp', function()
    require('dap.ui.widgets').preview()
end)
vim.keymap.set('n', '<Leader>df', function()
    local widgets = require('dap.ui.widgets')
    widgets.centered_float(widgets.frames)
end)
vim.keymap.set('n', '<Leader>ds', function()
    local widgets = require('dap.ui.widgets')
    widgets.centered_float(widgets.scopes)
end)
vim.keymap.set('n', '<leader>dn', function() require('dap-python').test_method() end)
vim.keymap.set('n', '<leader>dc', function() require('dap-python').test_class() end)
require("dap-python").setup("python3")
